/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "gtk40"

#define GTK_DATADIR "/opt/homebrew/share"

#define GTK_LIBDIR "/opt/homebrew/lib"

#define GTK_LOCALEDIR "/opt/homebrew/share/locale"

#define GTK_PRINT_BACKENDS "cups,file"

#define GTK_SYSCONFDIR "/opt/homebrew/etc"

#define HAVE_CAIRO_SCRIPT_INTERPRETER

#undef HAVE_CLOUDPROVIDERS

#undef HAVE_COLORD

#define HAVE_DLFCN_H 1

#undef HAVE_DMABUF

#define HAVE_FTW_H 1

#define HAVE_GETPAGESIZE 1

#define HAVE_GIO_UNIX

#define HAVE_GSTREAMER 1

#define HAVE_HARFBUZZ

#define HAVE_INTTYPES_H 1

#define HAVE_LOCALE_H 1

#define HAVE_MADVISE 1

#define HAVE_MEMORY_H 1

#define HAVE_MKOSTEMP 1

#define HAVE_MLOCK 1

#define HAVE_MMAP 1

#define HAVE_PANGOFT

#define HAVE_RANDR

#define HAVE_RANDR15

#define HAVE_SIGSETJMP

#define HAVE_STDINT_H 1

#define HAVE_STDLIB_H 1

#define HAVE_STRINGS_H 1

#define HAVE_STRING_H 1

#define HAVE_SYS_MMAN_H 1

#define HAVE_SYS_PARAM_H 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TIME_H 1

#define HAVE_SYS_TYPES_H 1

#undef HAVE_TRACKER3

#define HAVE_UINT128_T 1

#define HAVE_UNISTD_H 1

#define HAVE_XCURSOR 1

#define HAVE_XDAMAGE 1

#define HAVE_XFIXES 1

#define HAVE_XFREE_XINERAMA 1

#define HAVE_XGENERICEVENTS 1

#define HAVE_XKB 1

#define HAVE_XSYNC 1

#undef HAVE__NL_MEASUREMENT_MEASUREMENT

#undef HAVE__NL_PAPER_HEIGHT

#undef HAVE__NL_PAPER_WIDTH

#undef HAVE__NL_TIME_FIRST_WEEKDAY

#define ISO_CODES_PREFIX "/usr"

#define PACKAGE_VERSION "4.12.5"

#define XINPUT_2_2 1

#define XINPUT_2_4 1

